pipeline {
    agent any

    tools{
        nodejs 'NODE21'
    }

    stages {
       stage('Clone App Repo') {
          steps {
              
            sh '''
                rm -rf app
                git clone --branch main https://github.com/Zeezart/my-deen-and-i.git app
              '''
          }
        }


        stage('Install Dependencies') {
            steps {
                dir ('app'){
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir ('app'){
                   sh 'npm test'
                }
                
            }
        }

        stage('Build App') {
            steps {
                dir ('app'){
                    sh 'npm run build'
                }
               
            }
        }

        stage('Package Artifact') {
            steps {
                dir ('app'){
                    sh 'zip -r build.zip dist/'
                }
                
            }
        }

        stage('Copy Artifact to Server') {
            steps {
                // sh 'scp -i ~/.ssh/vibez-key build.zip ubuntu@3.91.99.212:/home/ubuntu/'
                sh 'scp -i /var/lib/jenkins/.ssh/vibez-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.zip ubuntu@3.91.99.212:/home/ubuntu/'


            }
        }

        stage('Trigger Ansible Deployment') {
            steps {
                dir("${env.WORKSPACE}") {
                  sh 'ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml'
                }
            }
        }
    }
}
