---

- name: Deploy React App
  hosts: "{{ env }}"
  become: yes
  vars:
    web_root: "/var/www/{{ env }}"

  tasks:

    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove old build (if any)
      file:
        path: "{{ web_root }}"
        state: absent

    - name: Create deploy directory
      file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'

    - name: Unzip app to web root
      unarchive:
        src: /home/ubuntu/build.zip
        dest: "{{ web_root }}"
        remote_src: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
