---
- name: Deploy Built React App to EC2
  hosts: webservers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove old app files
      file:
        path: /var/www/html
        state: absent

    - name: Recreate html directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Unzip the React app build to Nginx root
      unarchive:
        src: /home/ubuntu/build.zip
        dest: /var/www/html
        remote_src: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: restarted
        enabled: yes
